server:
  port: 8080

spring:
  application:
    name: AmazonKinesisService

aws:
  region: eu-north-1
  access-key:
  secret-key:

kinesis:
  stream-name: EmployeeStream

logging:
  level:
    root: INFO
    software.amazon.awssdk: INFO